Repository jonasbn/perl-workflow, pull requests merged in 2021-07, with the labels that each got.

#119 Close #107: allow configuration of the desired workflow class
  lib/Workflow/Config.pm
  lib/Workflow/Factory.pm
  t/TestApp/CustomWorkflow.pm
  t/workflow.t
  t/workflow_observer.xml
Labels: enhancement

#128 Message fixes
  lib/Workflow/Condition.pm
  lib/Workflow/Factory.pm
  lib/Workflow/State.pm
Labels: bug

#130 When using action groups, include 'default'-type actions
  lib/Workflow/State.pm
Labels: bug

#117 Remove SPOPS from the main Workflow tree
  dist.ini
  eg/ticket/log4perl.conf
  lib/Workflow/Persister/SPOPS.pm
  t/TestApp/Action/TicketCreate.pm
  t/TestApp/Action/TicketCreateType.pm
  t/TestApp/Ticket.pm
  t/log4perl.conf
  t/persister_spops.t
Labels: deprecation

#133 Remove empty Workflow::Condition::Nested class
  lib/Workflow/Condition/CheckReturn.pm
  lib/Workflow/Condition/GreedyOR.pm
  lib/Workflow/Condition/LazyAND.pm
  lib/Workflow/Condition/LazyOR.pm
  lib/Workflow/Condition/Nested.pm
  t/05_condition_nested.d/workflow_def_wfnest.xml
Labels: deprecation

#134 Remove empty Workflow::Action::Mailer action
  lib/Workflow/Action/Mailer.pm
  t/action_mailer.t
Labels: deprecation

#136 Rename Workflow::Action::InputField to Workflow::InputField
  lib/Workflow.pm
  lib/Workflow/Action.pm
  lib/Workflow/InputField.pm
  t/action_field.t
Labels: breakingchange

#138 Change the contract between the persister and the workflow wrt history
  lib/Workflow.pm
  lib/Workflow/Persister.pm
  lib/Workflow/Persister/DBI.pm
  lib/Workflow/Persister/File.pm
Labels: breakingchange, enhancement

#110 Refactor 'autorun' handling into a loop (from recursion)
  lib/Workflow.pm
Labels: breakingchange, enhancement

#145 Update reference to DateTime
  lib/Workflow/Persister/DBI.pm
Labels: todo

#144 Exclude coverage outside `lib/`
  t/05_condition_nested.t
  t/TestUtil.pm
  t/action.t
  t/action_field.t
  t/action_null.t
  t/action_validate.t
  t/add_config_bug.t
  t/base.t
  t/cached_conditions.t
  t/condition.t
  t/condition_evaluate.t
  t/config.t
  t/context-persists.t
  t/context.t
  t/exception.t
  t/factory.t
  t/factory_callback_config.t
  t/factory_subclass.t
  t/history.t
  t/log4perl.conf
  t/persister.t
  t/persister_dbi.t
  t/persister_dbi_extra_data.t
  t/persister_dbi_inherit.t
  t/persister_dbi_sqlite.t
  t/persister_file.t
  t/persister_random_id.t
  t/persister_uuid.t
  t/state.t
  t/state_perl.t
  t/uncached_conditions.t
  t/validator.t
  t/validator_has_required_field.t
  t/validator_in_enumerated_type.t
  t/validator_matches_date_format.t
  t/workflow.t
Labels: todo

#148 Instead of suppressing an exception, prevent it
  dist.ini
  lib/Workflow/Validator/MatchesDateFormat.pm
Labels: todo

#149 Improved test coverage using mocking and cheating
  lib/Workflow/Persister/DBI/AutoGeneratedId.pm
  lib/Workflow/Persister/DBI/SequenceId.pm
  t/TestDBUtil.pm
  t/persister_auto_generate_id.t
  t/persister_sequence_id.t
Labels: todo

#155 Eliminate warnings from configuration errors being printed on STDOUT
  lib/Workflow/Config/Perl.pm
Labels: todo

#157 Add B::Deparse support for Syntax::Keyword::Try
  .github/workflows/ci.yml
Labels: todo

#159 Convert dist.ini dependencies to cpanfile
  cpanfile
  dist.ini
  lib/Workflow.pm
Labels: maintenance
