Repository jonasbn/perl-workflow, pull requests merged in 2022-01, with the labels that each got.

#178 Addressed several Perl::Critic violation, several disabled project scope in rc file other locally, more work to be done, but this addresses somewhat issue #43 (closes #43)
  cpanfile
  lib/Workflow/Action/Null.pm
  lib/Workflow/Base.pm
  lib/Workflow/Factory.pm
  lib/Workflow/Persister/DBI.pm
  lib/Workflow/Persister/File.pm
  t/perlcriticrc
Labels: maintenance

#182 Document persister's handling of workflow context
  lib/Workflow/Factory.pm
  lib/Workflow/Persister.pm
  lib/Workflow/Persister/File.pm
Labels: breakingchange

#186 Correction to Perl::Critic configuration
  t/perlcriticrc
Labels: bug
